### ISSUE TITLE
[Team]

### ISSUE THREAD

**Issue by TheSpaceArmy** [PolyExtend/PolyExtend#11]
please add a team Badge to Gamefruit or it will be removed since that is the requirments

**Comment by mitsukaki** [comment]
Why is this a requirement? Some teams don't have a logo.

**Comment by Tromino** [comment]
Then it just shows as a broken image.

**Comment by ghost** [comment]
Also a Music badge is needed.

**Comment by TheSpaceArmy** [comment]
ya were Still Trying To Do That music one but no one has a good one

**Comment by ghost** [comment]
https://smallimage.in/o874x.png (It's transparent)

**Comment by ghost** [comment]
Team has been removed.

Issue Closed.
