### ISSUE TITLE
[Similarity Infringement] Logo's

### ISSUE THREAD

**Issue by artdude543** [PolyExtend/PolyExtend#13]
Hello,

The logo which was recently pushed [here](https://github.com/Tromino/PolyExtend/commit/0e9892960d37bd14bc64cf043e38534f4c256e4b) is similar to the original BEx logo found [here](https://cdn.exozone.net/bex-legacy/icon.png) of which  ExoZone owns the rights for. The logo is also infringing on the style guidelines for the BEx logo.

We would like to request that the logo is altered or changed to remove the similarity branding which could confuse our user base.

We understand that you want to make an alternative to xChat / BEx but copying (or using same styles) as ours is infringing rights we own along with playing fowl when it comes to development. This is not a competition to get the larger user base, people will come to the apps which they like and work well enough.

I hope you understand our concerns and listen to our requests as I like to talk to developers before pushing legal actions against projects.

Thanks,
artdude543 (ExoZone Developer)

**Comment by Tromino** [comment]
Yes, I can change it. Causing confusion wasn't the purpose of the logo, but I guess I could see it happening.
