### ISSUE TITLE
BeepBot Bots

### ISSUE THREAD

**Issue by artdude543** [PolyExtend/PolyExtend#9]
Can all bots which relate to BeepBot be removed from your bot listing please. We would like no association with this application other than official ones we (ExoZone) either support or ones we recommend our users to use. This also means that no other new ones can be added, which are bots provided by BeepBot.

The bots I can see listed are as followed:
- lovebuttbot
- beepbot
- tssnbot

Thanks,
artdude543

**Comment by mitsukaki** [comment]
Sure thing! I'll get on to this asap. They should be removed within 24 hours. Thank you for notifying us. Have a nice day,

lite20

**Comment by mitsukaki** [comment]
The boys have been removed. It may take a bit for them to be fully updated. If we missed any bots, please let me know.
